### ISSUE TITLE
Seems that Squeeze node of ONNX input model must have axes attribute, is it a bug or just feature?

### ISSUE THREAD

**Issue by wusongchao** [openppl-public/ppq#127]
I am using an ONNX model which contains a Squeeze operator without the ```axes``` attribute as ```quantize_onnx_model```'s input. It failed, the error messages are:
```
Squeeze_126(TargetPlatform.FP32) - inputs:['501'], outputs:['502']
Traceback (most recent call last):
  File "/Users/wusongchao/code/ppq/ppq/executor/torch.py", line 366, in __forward
    outputs = operation_forward_func(operation, inputs, self._executing_context)
  File "/Users/wusongchao/code/ppq/ppq/executor/op/torch/default.py", line 683, in Squeeze_forward
    [squeezing_tensor], axes = values, GET_ATTRIBUTE_FROM_OPERATION(op=op, attribute='axes', compulsive=True)
  File "/Users/wusongchao/code/ppq/ppq/executor/op/torch/base.py", line 78, in GET_ATTRIBUTE_FROM_OPERATION
    'However this value is missing from currecnt operation.')
KeyError: ('Operation Squeeze_126 is supposed to have a value of attribute axes. ', 'However this value is missing from currecnt operation.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppq-entrance.py", line 67, in <module>
    device=DEVICE, verbose=0)
  File "/Users/wusongchao/code/ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/Users/wusongchao/code/ppq/ppq/api/interface.py", line 274, in quantize_onnx_model
    collate_fn=collate_fn
  File "/Users/wusongchao/code/ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/Users/wusongchao/code/ppq/ppq/quantization/quantizer/base.py", line 61, in quantize
    executor.tracing_operation_meta(inputs=inputs)
  File "/Users/wusongchao/.pyenv/versions/3.7.11/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/Users/wusongchao/code/ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/Users/wusongchao/code/ppq/ppq/executor/torch.py", line 433, in tracing_operation_meta
    hooks=hooks)
  File "/Users/wusongchao/code/ppq/ppq/executor/torch.py", line 394, in __forward
    raise RuntimeError(f'Error happens when dealing with operation {str(operation)}')
RuntimeError: Error happens when dealing with operation Squeeze_126(TargetPlatform.FP32) - inputs:['501'], outputs:['502']
```
So i was guided to the definition of ```Squeeze_forward```, the documentation here claims that ```axes``` is a optional field(which is the same as [ONNX IR doc](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Squeeze)).

https://github.com/openppl-public/ppq/blob/f1cdb6d9735dc51a7f4dc56e9866e15e1624aaab/ppq/executor/op/torch/default.py#L655-L679

However, the implementation call ```GET_ATTRIBUTE_FROM_OPERATION``` with ```compulsive=True```. Since the Squeeze operator inside my model do not contains the ```axes``` attribute, it throws the exception that i pasted in the beginning.

https://github.com/openppl-public/ppq/blob/f1cdb6d9735dc51a7f4dc56e9866e15e1624aaab/ppq/executor/op/torch/default.py#L680-L690

So i wonder, is such mandatory needed of Squeeze operator ```axes``` field a intended feature, or just a bug?

**Comment by ZhangZhiPku** [comment]
说起来你可能不信，ppq 目前希望你送进来的模型是opset11的，你这个sequeeze上面可以不带axes的行为是opset13的...
你可以直接把那段代码改了让他能通过...

**Comment by wusongchao** [comment]
> 说起来你可能不信，ppq 目前希望你送进来的模型是opset11的，你这个sequeeze上面可以不带axes的行为是opset13的... 你可以直接把那段代码改了让他能通过...
> 
> 至于注释，emm我是从onnx官网抄的，似乎抄错版本了

谢谢解惑

**Comment by wusongchao** [comment]
btw，想请教一下为什么 Squeeze 默认没有被带进 PASSIVE_OPERATIONS 里面呢

**Comment by ZhangZhiPku** [comment]
让我偷偷写进去，我们当做无事发生
