### ISSUE TITLE
RuntimeError: Error building extension 'PPQ_Cuda_Impls': [1/6] :/usr/local/cuda-10.2/bin/nvcc

### ISSUE THREAD

**Issue by ymzx** [openppl-public/ppq#218]
!! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "/root/anaconda3/envs/pytorch/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/core/ffi.py", line 16, in <module>
    __CUDA_EXTENTION__ = load(
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1449, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'PPQ_Cuda_Impls': [1/6] :/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cuda/linear.cu -o linear.cuda.o
FAILED: linear.cuda.o
:/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cuda/linear.cu -o linear.cuda.o
/bin/sh: :/usr/local/cuda-10.2/bin/nvcc: No such file or directory
[2/6] :/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cuda/sort.cu -o sort.cuda.o
FAILED: sort.cuda.o
:/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cuda/sort.cu -o sort.cuda.o
/bin/sh: :/usr/local/cuda-10.2/bin/nvcc: No such file or directory
[3/6] :/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cuda/train.cu -o train.cuda.o
FAILED: train.cuda.o
:/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cuda/train.cu -o train.cuda.o
/bin/sh: :/usr/local/cuda-10.2/bin/nvcc: No such file or directory
[4/6] c++ -MMD -MF export.o.d -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/export.cc -o export.o
FAILED: export.o
c++ -MMD -MF export.o.d -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/export.cc -o export.o
c++: error: unrecognized command line option ‘-std=c++14’
[5/6] c++ -MMD -MF hist_mse.o.d -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cpu/hist_mse.cc -o hist_mse.o
FAILED: hist_mse.o
c++ -MMD -MF hist_mse.o.d -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /root/anaconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /root/anaconda3/envs/pytorch/lib/python3.8/site-packages/ppq-0.6.5-py3.8.egg/ppq/csrc/cpu/hist_mse.cc -o hist_mse.o
c++: error: unrecognized command line option ‘-std=c++14’
ninja: build stopped: subcommand failed.

**Comment by ymzx** [comment]
> 如果你在安装时显示了上述信息，不用做额外处置，这些是编译错误。 PPQ允许你在编译失败时正常使用程序功能，并且程序可以成功安装。
> 
> 如果你在使用过程中出现了上述信息，这可能是由于你的代码中存在子句with ENABLE_CUDA_KERNEL()， 将这些内容移除即可。

在使用过程中出现了上述信息，但是代码中不存在子句with ENABLE_CUDA_KERNEL()

`from ppq import *
from ppq.api import *
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# modify configuration below:
WORKING_DIRECTORY     = 'qm-lenet'                             # choose your working directory
TARGET_PLATFORM       = TargetPlatform.NXP_INT8               # choose your target platform
MODEL_TYPE            = NetworkFramework.ONNX                 # or NetworkFramework.CAFFE
INPUT_LAYOUT          = 'chw'                             # input data layout, chw or hwc
NETWORK_INPUTSHAPE    = [16, 1, 28, 28]                   # input shape of your network
CALIBRATION_BATCHSIZE = 16                                # batchsize of calibration dataset
EXECUTING_DEVICE      = 'cuda'                            # 'cuda' or 'cpu'.
REQUIRE_ANALYSE       = True
DUMP_RESULT           = False

# -------------------------------------------------------------------
# SETTING 对象用于控制 PPQ 的量化逻辑
# 当你的网络量化误差过高时，你需要修改 SETTING 对象中的参数来进行特定的优化
# -------------------------------------------------------------------
SETTING = UnbelievableUserFriendlyQuantizationSetting(
    platform = TARGET_PLATFORM, finetune_steps = 2500,
    finetune_lr = 1e-3, calibration = 'percentile',
    equalization = True, non_quantable_op = None)
SETTING = SETTING.convert_to_daddy_setting()

print('正准备量化你的网络，检查下列设置:')
print(f'WORKING DIRECTORY    : {WORKING_DIRECTORY}')
print(f'TARGET PLATFORM      : {TARGET_PLATFORM.name}')
print(f'NETWORK INPUTSHAPE   : {NETWORK_INPUTSHAPE}')
print(f'CALIBRATION BATCHSIZE: {CALIBRATION_BATCHSIZE}')


mnist = datasets.MNIST('../data', train=False, transform=transforms.Compose([transforms.ToTensor()]))
mnist_data = mnist.data.view(-1, 1, 28, 28).float()
dataset_len = mnist_data.shape[0]
#mnist_data = mnist_data/255
calibration_dataset = mnist_data

dataloader = DataLoader(dataset=calibration_dataset,batch_size=32, shuffle=True)

quantized = quantize(
    working_directory=WORKING_DIRECTORY, setting=SETTING,
    model_type=MODEL_TYPE, executing_device=EXECUTING_DEVICE,
    input_shape=NETWORK_INPUTSHAPE, target_platform=TARGET_PLATFORM,
    dataloader=dataloader, calib_steps=256)

# -------------------------------------------------------------------
# 如果你需要执行量化后的神经网络并得到结果，则需要创建一个 executor
# 这个 executor 的行为和 torch.Module 是类似的，你可以利用这个东西来获取执行结果
# 请注意，必须在 export 之前执行此操作。
# -------------------------------------------------------------------
executor = TorchExecutor(graph=quantized)
# output = executor.forward(input)

# -------------------------------------------------------------------
# 导出 PPQ 执行网络的所有中间结果，该功能是为了和硬件对比结果
# 中间结果可能十分庞大，因此 PPQ 将使用线性同余发射器从执行结果中采样
# 为了正确对比中间结果，硬件执行结果也必须使用同样的随机数种子采样
# 查阅 ppq.util.fetch 中的相关代码以进一步了解此内容
# 查阅 ppq.api.fsys 中的 dump_internal_results 函数以确定采样逻辑
# -------------------------------------------------------------------
if DUMP_RESULT:
    dump_internal_results(
        graph=quantized, dataloader=dataloader,
        dump_dir=WORKING_DIRECTORY, executing_device=EXECUTING_DEVICE)

# -------------------------------------------------------------------
# PPQ 计算量化误差时，使用信噪比的倒数作为指标，即噪声能量 / 信号能量
# 量化误差 0.1 表示在整体信号中，量化噪声的能量约为 10%
# 你应当注意，在 graphwise_error_analyse 分析中，我们衡量的是累计误差
# 网络的最后一层往往都具有较大的累计误差，这些误差是其前面的所有层所共同造成的
# 你需要使用 layerwise_error_analyse 逐层分析误差的来源
# -------------------------------------------------------------------
print('正计算网络量化误差(SNR)，最后一层的误差应小于 0.1 以保证量化精度:')
reports = graphwise_error_analyse(
    graph=quantized, running_device=EXECUTING_DEVICE, steps=256,
    dataloader=dataloader, collate_fn=lambda x: x.to(EXECUTING_DEVICE))
for op, snr in reports.items():
    if snr > 0.1: ppq_warning(f'层 {op} 的累计量化误差显著，请考虑进行优化')

if REQUIRE_ANALYSE:
    print('正计算逐层量化误差(SNR)，每一层的独立量化误差应小于 0.1 以保证量化精度:')
    layerwise_error_analyse(graph=quantized,
                            running_device=EXECUTING_DEVICE,
                            steps=256,
                            interested_outputs=None,
                            dataloader=dataloader, collate_fn=lambda x: x.to(EXECUTING_DEVICE))

export(working_directory=WORKING_DIRECTORY,
       quantized=quantized, platform=TargetPlatform.ONNXRUNTIME)`

**Comment by ZhangZhiPku** [comment]
让我来研究一下，于此同时你可以尝试直接删除ppq.ffi中的编译语句

**Comment by ZhangZhiPku** [comment]
问题将在 #222 此次提交后修复
