### ISSUE TITLE
A bug when export file

### ISSUE THREAD

**Issue by Charles-258** [openppl-public/ppq#219]
### 当我在导出的时候platform=TargetPlatform.ONNXRUNTIME会出现以下报错，但是platform=TargetPlatform.ONNX就不会

网络量化结束，正在生成目标文件:
Traceback (most recent call last):
  File "/tmp/pycharm_project_280/ppq/programeetrance.py", line 188, in <module>
    config_save_to=os.path.join(WORKING_DIRECTORY, 'quant_cfg.json'))
  File "/home/wyy/anaconda3/envs/py_37/lib/python3.7/site-packages/ppq/api/interface.py", line 610, in export_ppq_graph
    exporter.export(file_path=graph_save_to, config_path=config_save_to, graph=graph, **kwargs)
  File "/home/wyy/anaconda3/envs/py_37/lib/python3.7/site-packages/ppq/parser/onnxruntime_exporter.py", line 366, in export
    graph = self.prepare_graph(graph)
  File "/home/wyy/anaconda3/envs/py_37/lib/python3.7/site-packages/ppq/parser/onnxruntime_exporter.py", line 361, in prepare_graph
    quant_param_to_int=quant_parameter_to_int)
  File "/home/wyy/anaconda3/envs/py_37/lib/python3.7/site-packages/ppq/parser/onnxruntime_exporter.py", line 315, in convert_operation
    graph=graph, var=var, config=config, related_op=op, meta=meta)
  File "/home/wyy/anaconda3/envs/py_37/lib/python3.7/site-packages/ppq/parser/onnxruntime_exporter.py", line 74, in insert_quant_on_variable
    scale  = convert_any_to_torch_tensor(config.scale.clone(), dtype=torch.float32)
AttributeError: 'NoneType' object has no attribute 'clone'

**Comment by ZhangZhiPku** [comment]
问题将在下一次更新中修复，目前你可以在报错的第74行前加一个判断
if config.scale == None: return related_op

**Comment by Charles-258** [comment]
> if config.scale == None: return related_op

这个问题同样也出现在了第109行，请问也是这样修改吗

**Comment by ZhangZhiPku** [comment]
可以的
