### ISSUE TITLE
RuntimeError: Error happens when dealing with operation ConstantOfShape_1246(TargetPlatform.SOI)

### ISSUE THREAD

**Issue by shhn1** [openppl-public/ppq#295]
我执行了ppq/samples/Tutorial/quantize.py，使用模型是swin-transformer，target platform是TRT_INT8，出现了如下报错：
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/executor/torch.py", line 541, in __forward
    outputs = operation_forward_func(operation, inputs, self._executing_context)
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/executor/op/torch/default.py", line 1197, in ConstantOfShape_forward
    output = torch.Tensor().new_full(
TypeError: new_full(): argument 'size' must be tuple of ints, not list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "quantize_test.py", line 71, in <module>
    quantized = quantize_onnx_model(
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/api/interface.py", line 259, in quantize_onnx_model
    quantizer.quantize(
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/quantization/quantizer/base.py", line 61, in quantize
    executor.tracing_operation_meta(inputs=inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/executor/torch.py", line 603, in tracing_operation_meta
    self.__forward(
  File "/usr/local/lib/python3.8/dist-packages/ppq-0.6.6-py3.8.egg/ppq/executor/torch.py", line 568, in __forward
    raise RuntimeError(f'Error happens when dealing with operation {str(operation)}') from _
RuntimeError: Error happens when dealing with operation ConstantOfShape_1246(TargetPlatform.SOI) - inputs:['onnx::ConstantOfShape_4472'], outputs:['onnx::Concat_4473']

**Comment by ZhangZhiPku** [comment]
问题已经收到，你可以修改ppq/executor/op/torch/default.py, line 1197 为如下的语句
output = torch.Tensor().new_full(size=tuple(shape.tolist()), fill_value=fill_value)

**Comment by shhn1** [comment]
> 问题已经收到，你可以修改ppq/executor/op/torch/default.py, line 1197 为如下的语句 output = torch.Tensor().new_full(size=tuple(shape.tolist()), fill_value=fill_value)

这个方法我试过了，但是没有解决哎，还是有一样的报错

**Comment by ZhangZhiPku** [comment]
改错位置了吧...你可以直接加一句print('Hello world') 在他前面，看看执行的时候会不会打印

**Comment by shhn1** [comment]
<img width="954" alt="截屏2022-11-15 17 57 41" src="https://user-images.githubusercontent.com/55838930/201889503-b48fd62d-e50e-4df6-9bb5-67d759fd92e6.png">

位置没有改错，也能输出print的内容

**Comment by ZhangZhiPku** [comment]
好像是这个 ConstantOfShape 的 foward 逻辑哪有问题... 他现在给你报错是要一个 tuple of ints, 而不是 tuple，难道你这个shape是浮点数？

**Comment by shhn1** [comment]
> 好像是这个 ConstantOfShape 的 foward 逻辑哪有问题... 他现在给你报错是要一个 tuple of ints, 而不是 tuple，难道你这个shape是浮点数？ 你可以把模型发我瞅一眼

找到问题了，就是shape竟然是个浮点数，转成int就好了～谢谢！

**Comment by shhn1** [comment]
可以顺便请教一个问题吗？我看sample中的校准集都是一些随机生成的数据，相比于使用模型的训练/验证集的数据作为校准集，这样精确度是会更低一点吧？

**Comment by ZhangZhiPku** [comment]
那玩意不是精度低一点的问题，那玩意精度就完全不对...

**Comment by shhn1** [comment]
好的，感谢
