### ISSUE TITLE
Samples/Bert_sample.py 运行时报错

### ISSUE THREAD

**Issue by yc-wang00** [openppl-public/ppq#358]
我使用huggingface原生的模型导出命令 将pytorch文件转换成onnx文件。然后直接run bert_sample.py， 遇到以下错误:

```
[Warning] Unexpected input value of operation Gather_95, recieving "None" at its input 1
Traceback (most recent call last):
  File "/ppq-test/ppq/executor/torch.py", line 535, in __forward
    outputs = operation_forward_func(operation, inputs, self._executing_context)
  File "/ppq-test/ppq/executor/op/torch/default.py", line 1084, in Gather_forward
    indices = indices.long()
AttributeError: 'NoneType' object has no attribute 'long'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bert_sample.py", line 109, in <module>
    executor.tracing_operation_meta(inputs=collate_fn(dataset[0]))
  File "/opt/python3.8.6/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/ppq-test/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/ppq-test/ppq/executor/torch.py", line 597, in tracing_operation_meta
    self.__forward(
  File "/ppq-test/ppq/executor/torch.py", line 562, in __forward
    raise RuntimeError(f'Error happens when dealing with operation {str(operation)}') from _
RuntimeError: Error happens when dealing with operation Gather_95(Type: Gather, Num of Input: 2, Num of Output: 1)
```

错误复现方式:
step1. bert pytorch模型获取:
```
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Load tokenizer and PyTorch weights form the Hub
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
pt_model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
# Save to disk
tokenizer.save_pretrained("bert.pt")
pt_model.save_pretrained("bert.pt")
```
step2. bert pytorch to onnx:
```python -m transformers.onnx --model=bert.pt bert.onnx```

step3 run bert_sample.py
```python3 bert_sample.py```

**Comment by ZhangZhiPku** [comment]
你这gather的输入是空的？

**Comment by yc-wang00** [comment]
这里是模型连接 https://drive.google.com/file/d/1Hk2HojjiRWTkDxubkyvakj8YBHqdrnLR/view?usp=share_link
另外上述代码应该可以直接生成bert.onnx

谢谢

**Comment by ZhangZhiPku** [comment]
好像gather_95的第二个输入也是网络的输入，你并没有给它传入相对应的值

**Comment by ZhangZhiPku** [comment]
你这个报错挺猛啊...这直接cuda报错了，这个一般是由于ppq的cuda kernel跟什么其他东西冲突了，你可以关闭cuda kernel试试
