### ISSUE TITLE
量化yolov8导出的onnx报错

### ISSUE THREAD

**Issue by Prometheus-first** [openppl-public/ppq#387]
代码如下：
[code.txt](https://github.com/openppl-public/ppq/files/10764829/code.txt)

报错：
正准备量化你的网络，检查下列设置:
WORKING DIRECTORY    : working
TARGET PLATFORM      : PPL_CUDA_INT8
NETWORK INPUTSHAPE   : [1, 3, 1920, 1080]
CALIBRATION BATCHSIZE: 16
152 File(s) Loaded.
Loaded sample 0, shape: torch.Size([1, 3, 1920, 1080])
Loaded sample 1, shape: torch.Size([1, 3, 1920, 1080])
Loaded sample 2, shape: torch.Size([1, 3, 1920, 1080])
Loaded sample 3, shape: torch.Size([1, 3, 1920, 1080])
Loaded sample 4, shape: torch.Size([1, 3, 1920, 1080])
Batch Shape: torch.Size([16, 3, 1920, 1080])
[Warning] Compling Kernels... Please wait (It will take a few minutes).
E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ���
Traceback (most recent call last):
  File "E:\study\workDir\cv\liangHua\1.py", line 96, in <module>
    with ENABLE_CUDA_KERNEL():
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\ppq\api\interface.py", line 944, in __init__
    CUDA_COMPLIER.complie()
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\ppq\core\ffi.py", line 28, in complie
    self.__CUDA_EXTENTION__ = load(
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\torch\utils\cpp_extension.py", line 1610, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\torch\utils\cpp_extension.py", line 2055, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\site-packages\torch\utils\cpp_extension.py", line 2195, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\studySoftware\anaconda\files\envs\lianghua\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

进程已结束,退出代码1

**Comment by ZhangZhiPku** [comment]
你没有安装编译环境

你可以选择安装编译环境：visual studio 2019
或者注释掉 with ENABLE_CUDA_KERNEL():

**Comment by Prometheus-first** [comment]
报错之后我去安装了一下vs2017，是这个版本不可以用吗，不可以的话我去改一下vs版本

**Comment by ZhangZhiPku** [comment]
你不止要安装vs2019，而且要把它的cl.exe那个文件写入到系统路径中
而且vs2017好像确实不行
