### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by zack-rgb** [openppl-public/ppq#393]

**Comment by zack-rgb** [comment]
Error building extension 'PPQ_Cuda_Impls': [1/5] :/usr/local/cuda:/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output linear.cuda.o.d -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/miniconda3/envs/ppq_1/lib/python3.7/site-packages/torch/include -isystem /usr/local/miniconda3/envs/ppq_1/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/miniconda3/envs/ppq_1/lib/python3.7/site-packages/torch/include/TH -isystem /usr/local/miniconda3/envs/ppq_1/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /usr/local/miniconda3/envs/ppq_1/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /usr/local/miniconda3/envs/ppq_1/lib/python3.7/site-packages/ppq/csrc/cuda/linear.cu -o linear.cuda.o 
FAILED: linear.cuda.o

**Comment by ZhangZhiPku** [comment]
你这...错误不完整啊..

**Comment by zack-rgb** [comment]
[Warning] Compling Kernels... Please wait (It will take a few minutes).
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1906, in _run_ninja_build
    env=env)
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "1.py", line 58, in <module>
    with ENABLE_CUDA_KERNEL():
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/api/interface.py", line 944, in __init__
    CUDA_COMPLIER.complie()
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/core/ffi.py", line 39, in complie
    extra_cflags=['-O3'])
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1296, in load
    keep_intermediates=keep_intermediates)
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1518, in _jit_compile
    is_standalone=is_standalone)
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1626, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'PPQ_Cuda_Impls': [1/5] :/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/TH -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /usr/local/miniconda3/envs/ppq/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/csrc/cuda/linear.cu -o linear.cuda.o 


:/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/TH -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /usr/local/miniconda3/envs/ppq/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/csrc/cuda/train.cu -o train.cuda.o 
/bin/sh: 1: :/usr/local/cuda:/usr/local/cuda/bin/nvcc: not found
[4/5] c++ -MMD -MF export.o.d -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/TH -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /usr/local/miniconda3/envs/ppq/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/csrc/export.cc -o export.o 
FAILED: export.o 
c++ -MMD -MF export.o.d -DTORCH_EXTENSION_NAME=PPQ_Cuda_Impls -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/TH -isystem /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /usr/local/miniconda3/envs/ppq/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/csrc/export.cc -o export.o 
In file included from /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/csrc/cuda/linear.h:1,
                 from /usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/csrc/export.cc:1:
/usr/local/miniconda3/envs/ppq/lib/python3.7/site-packages/ppq/csrc/cuda/common.cuh:1:11: fatal error: cuda.h: 没有那个文件或目录
    1 | # include <cuda.h>
      |           ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.


这是一个报错，中间有很多一样的，所以没全复制

**Comment by ZhangZhiPku** [comment]
你的环境中没有正确安装cuda，你可以尝试安装cuda或者移除with ENABLE_CUDA_KERNEL语句

**Comment by YaoChengTang** [comment]
你的cuda环境变量没有设置正确，echo $CUDA_HOME，检查一下CUDA_HOME，应该是/usr/local/cuda而不是:/usr/local/cuda，修改bash_rc之类的文件，export CUDA_HOME=/usr/local/cuda
