### ISSUE TITLE
模型大小100M ，这量化过程太吃现存了吧，是不是哪里有问题？2080ti

### ISSUE THREAD

**Issue by cqray1990** [openppl-public/ppq#397]
[17:01:12] PPQ Parameter Quantization Pass Running ...    Finished.
Calibration Progress(Phase 1): 100%|██████████| 32/32 [00:04<00:00,  7.91it/s]
Finished.
[17:01:17] PPQ Quantization Alignment Pass Running ...    Finished.
[17:01:17] PPQ Passive Parameter Quantization Running ... Finished.
[17:01:17] PPQ LSQ Optimization Running ...               
Check following parameters:
Is Scale Trainable:        True
Interested Layers:         []
Collecting Device:         gpu
Num of blocks:             29
Learning Rate:             1e-05
Steps:                     500
Gamma:                     0.0

Traceback (most recent call last):
  File "ppq/ProgramEntrance.py", line 97, in <module>
    quantized = quantize_native_model(
  File "ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "ppq/ppq/api/interface.py", line 530, in quantize_native_model
    quantizer.quantize(
  File "ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "ppq/ppq/quantization/quantizer/base.py", line 78, in quantize
    quant_pipeline.optimize(
  File "ppq/ppq/quantization/optim/base.py", line 81, in optimize
    optim_pass.optimize(graph=graph, **kwargs)
  File "ppq/ppq/quantization/optim/training.py", line 842, in optimize
    qt_inputs, fp_outputs = self.collect(
  File "ppq/ppq/quantization/optim/training.py", line 289, in collect
    if collate_fn is not None: data = collate_fn(data)
  File "ppq/ProgramEntrance.py", line 104, in <lambda>
    collate_fn=lambda x: x.to(EXECUTING_DEVICE),  # collate_fn 跟 torch dataloader 的 collate fn 是一样的，用于数据预处理，
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.75 GiB total capacity; 8.43 GiB already allocated; 35.50 MiB free; 9.01 GiB reserved in total by PyTorch)

**Comment by ZhangZhiPku** [comment]
你似乎需要将 collecting_device 切换为 cpu

**Comment by cqray1990** [comment]
> 你似乎需要将 collecting_device 切换为 cpu

  为什么以下把所有的校准图片加载到内存中，这图片一多，都跑不了吧

**Comment by ZhangZhiPku** [comment]
在下一期视频中我们会解释这个问题

**Comment by ZhangZhiPku** [comment]
您可以查看这个视频来了解量化训练的相关内容，以及ppq为何需要缓存训练数据：
https://www.bilibili.com/video/BV13s4y1D73L
