### ISSUE TITLE
通过PPQ量化后的模型，无法正常通过openvino接口推理模型

### ISSUE THREAD

**Issue by Elasine** [openppl-public/ppq#420]
后端量化部署平台：TargetPlatform.OPENVINO_INT8
1. 通过PPQ工具执行量化流程及分析量化误差
2. 将量化后的ppq计算图保存为openvino模型
3. 初始化openvino推理引擎，通过openvino库的读取编译接口对量化后的模型进行读取编译: 
    首先用read_model()读取模型文件，然后用compile_model()编译到指定的设备（编译出错）,出错具体如下
model = self.openvino_executor.compile_model(module, device_name="CPU")
  File "/home/{$user}/.local/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: vector::_M_fill_insert
4. 针对出错，调用了openvino的C++接口进行了调用调试分析，能看到是申请内存超了，但一时难以确定出是哪一层算子出错，这个出错的原因不知道是 计算图进行export_ppq_graph操作出错，还是openvino不支持相关量化层出错导致，有点懵，所以请教下，怎么具体分析这个问题

**Comment by ZhangZhiPku** [comment]
我也不知道是怎么回事，你可以把网络截断从而找到是那一个算子出的问题

**Comment by Elasine** [comment]
> 我也不知道是怎么回事，你可以把网络截断从而找到是那一个算子出的问题
感谢感谢，我之后又把量化后的计算图又以TargetPlatform.ONNXRUNTIME平台策略导出保存，发现是Reshape层有问题
 Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main()
  File "main.py", line 169, in main
    ppq.test(onnx_path,calib_algo,config_path)
  File "main.py", line 148, in test
    onnx_result = inference(sample,openvino_model)
  File "/*/Deploy/ONNX/infer.py", line 44, in inference
    sess = ort.InferenceSession(onnx_path, providers=['CPUExecutionProvider'])
  File "/home/$user/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in            __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/$user/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in            _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from *.onnx failed:This is an invalid model. In Node, ("/**/embeddings/Reshape", Reshape, "", -1) : ("/*/embeddings/patch_embedding/Conv_outpu           t_0": tensor(float),"1686": tensor(int64),) -> ("/*/embeddings/Reshape_output_0": tensor(float),) , Error Unrecognized attribute: allowzero for operator Reshape
这个是因为不支持Reshape层吗？  
（当时量化之前使用的onnx模型，其opset设置的是16）

**Comment by ZhangZhiPku** [comment]
我猜是你的opset太高了，onnxruntime不认你这个reshape
他好像说你的reshape上面有个allowzero 属性，这个属性一般是设置为空的，但是你的模型似乎设定了这个属性。

**Comment by Elasine** [comment]
感谢回复！目前降低了opset的version为14，还是出现了两个问题：
1. 将待量化的onnx模型算子opset设置为了14,经过ppq量化出来的模型算子的opset为13，是不是ppq限制了转换opset的版本
2. 对于opset_vesion为14的reshape算子，有allow_zero这个属性，但是opset_version为13的reshape算子，没有allow_zero这个属性（详见http://www.xavierdupre.fr/app/mlprodict/helpsphinx/onnxops/onnx__Reshape.html#reshape-13），ppq在转换计算图后，opset_version为13，reshape却有allow_zero这个属性
![image](https://user-images.githubusercontent.com/33031095/230774814-dee10e71-73f1-418a-88c5-a0065b5e4c2c.png)
![image](https://user-images.githubusercontent.com/33031095/230774859-a0cd0612-d1c6-458f-974b-00c2c9314398.png)

**Comment by ZhangZhiPku** [comment]
是的，ppq最高支持opset13
