### ISSUE TITLE
onnx模型量化报错，IndexError: list index out of range

### ISSUE THREAD

**Issue by JinXiaozhao** [openppl-public/ppq#476]
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1606, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

模型是从TensorFlow转换的onnx模型，模型输入为[-1,10,122]，校验集数据为[2008,10,122]；
请问如下参数是否正确，如错误请问应该填哪些？
INPUT_LAYOUT = 'chw'
NETWORK_INPUTSHAPE = [1, 10, 122]
CALIBRATION_BATCHSIZE = 2088

加载校验集数据函数，是否需要修改？

```
def load_calibration_dataset_usad():
    datas = np.load('/home/ppq/data.npy')
    res = [datas[i:i+1] for i in range(datas.shape[0])]
    return res
```

**Comment by ZhangZhiPku** [comment]
你这个八成是因为环境有问题....我感觉你的torch没带cuda

**Comment by JinXiaozhao** [comment]
感谢回复，第一个问题解决了，但是量化中报错如下：
```
Traceback (most recent call last):
  File "ProgramEntrance.py", line 107, in <module>
    quantized = quantize_native_model(
  File "/home/ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/home/ppq/ppq/api/interface.py", line 530, in quantize_native_model
    quantizer.quantize(
  File "/home/ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/home/ppq/ppq/quantization/quantizer/base.py", line 69, in quantize
    quant_pipeline.optimize(
  File "/home/ppq/ppq/quantization/optim/base.py", line 81, in optimize
    optim_pass.optimize(graph=graph, **kwargs)
  File "/home/ppq/ppq/core/defs.py", line 54, in _wrapper
    return func(*args, **kwargs)
  File "/home/ppq/ppq/quantization/optim/calibration.py", line 176, in optimize
    self.calibrate(desc='Calibration Progress(Phase 1)', dataloader=dataloader,
  File "/home/ppq/ppq/quantization/optim/calibration.py", line 116, in calibrate
    data = self._collate_fn(data)
  File "ProgramEntrance.py", line 114, in <lambda>
    collate_fn=lambda x: x.to(EXECUTING_DEVICE),  # collate_fn 跟 torch dataloader 的 collate fn 是一样的，用于数据预处理，
AttributeError: 'numpy.ndarray' object has no attribute 'to'
```

**Comment by ZhangZhiPku** [comment]
你的collate_fn写的好像有问题，这个函数是数据预处理函数，你的数据是numpy.ndarray类型的，你不能直接使用.to函数，你应该先将他转换为torch.tensor

**Comment by JinXiaozhao** [comment]
那我使用原生接口的话，如下参数是否正确，如有错误请帮忙指出？
模型是从TensorFlow转换的onnx模型，模型输入为[-1,10,122]，校验集数据为[2008,10,122]；
```
INPUT_LAYOUT = 'chw'
NETWORK_INPUTSHAPE = [1, 10, 122]
CALIBRATION_BATCHSIZE = 2088
```

**Comment by ZhangZhiPku** [comment]
啊？啥是原生接口...

**Comment by JinXiaozhao** [comment]
ppq/ProgramEntrance_1.py代码中加载数据的接口

**Comment by ZhangZhiPku** [comment]
好像是不太对，你似乎应该写成

INPUT_LAYOUT = 'chw'
NETWORK_INPUTSHAPE = [1, 10, 122]
CALIBRATION_BATCHSIZE = 32

这样在calibration时将把相邻的32个样本数据打包成batch，并进行网络校准。
如果您设置为2088，可能显存不够。
