### ISSUE TITLE
ProgramEntrance_2.py 执行报错

### ISSUE THREAD

**Issue by zt706** [openppl-public/ppq#478]
环境使用 stephen222/ppq:ubuntu18.04_cuda11.4_cudnn8.4_trt8.4.1.5 容器，
代码使用最新master 分支

[Warning] Compling Kernels... Please wait (It will take a few minutes).
Traceback (most recent call last):
  File "ProgramEntrance_2.py", line 293, in <module>
    dispatching = PFL.Dispatcher(graph=graph).dispatch(
  File "/workspace/ppq/ppq/scheduler/dispatchers.py", line 202, in dispatch
    quant_operations = search_engine.opset_matching(
  File "/workspace/ppq/ppq/IR/search.py", line 610, in opset_matching
    partial_matchings = self._opset_matching(
  File "/workspace/ppq/ppq/IR/search.py", line 484, in _opset_matching
    if ep_expr is not None and ep_expr(op):
  File "/workspace/ppq/ppq/scheduler/dispatchers.py", line 205, in <lambda>
    ep_expr = lambda x: (x.type not in quant_types) or x.is_boundary,
TypeError: argument of type 'method' is not iterable

**Comment by ZhangZhiPku** [comment]
这还是个挺核心的错误，用ProgramEntrance_1 不会有这个错误吗？好像都会调用到这个地方的

**Comment by zt706** [comment]
> 这还是个挺核心的错误，用ProgramEntrance_1 不会有这个错误吗？好像都会调用到这个地方的

ProgramEntrance_1 不会报错

**Comment by ZhangZhiPku** [comment]
让我们偷偷发一下模型？

**Comment by zt706** [comment]
你好，都是官方代码，模型默认是 resnet18

唯一改动是：https://github.com/openppl-public/ppq/blob/master/ProgramEntrance_2.py#L234 
这里用 calibration_dataloader = [torch.zeros(size=[1,3,224,224]) for _ in range(32)]

**Comment by ersong2022** [comment]
这个问题有解决了吗？我也遇到这个问题了

**Comment by zhuleia** [comment]
您好，这个bug解决了，我在QAT中遇到了这个bug
