### ISSUE TITLE
使用 onnxruntime 加速网络出错

### ISSUE THREAD

**Issue by lDarryll** [openppl-public/ppq#481]
### 作者你好，照着rep中例子抄了一下，但是报错，可以帮指点一下吗，谢谢

**代码如下：**

```python
import torch
from ppq import *
from ppq.api import *
import torchvision.transforms as transforms
from tqdm import tqdm
from PIL import Image

QUANT_PLATFROM = TargetPlatform.ONNXRUNTIME
MODEL          = 'models/yolov5s.v5.onnx'
INPUT_SHAPE    = [1, 3, 640, 640]
# SAMPLES        = [torch.rand(size=INPUT_SHAPE) for _ in range(256)] # rewirte this to use real data.
DEVICE         = 'cuda'
FINETUNE       = False
QS             = QuantizationSettingFactory.default_setting()
EXECUTING_DEVICE = 'cuda'
REQUIRE_ANALYZE  = True

CALIBRATION_PATH = '/Data1/zengsheng/works/dl_works/ppq_works/yolo_model_zoo/coco128/images/train2017'


# create dataloader
imgs = []
trans = transforms.Compose([
    transforms.Resize([640, 640]),  # [h,w]
    transforms.ToTensor(),
])
for file in os.listdir(path=CALIBRATION_PATH):
    path = os.path.join(CALIBRATION_PATH, file)
    img = Image.open(path).convert('RGB')
    img = trans(img)
    imgs.append(img) # img is 0 - 1

from torch.utils.data import DataLoader
dataloader = DataLoader(dataset=imgs, batch_size=1)

# -------------------------------------------------------------------
# 下面向你展示了常用参数调节选项：
# -------------------------------------------------------------------
QS.lsq_optimization = FINETUNE                                  # 启动网络再训练过程，降低量化误差
QS.lsq_optimization_setting.steps = 10                         # 再训练步数，影响训练时间，500 步大概几分钟
QS.lsq_optimization_setting.collecting_device = 'cuda'          # 缓存数据放在那，cuda 就是放在 gpu，如果显存超了你就换成 'cpu'

print('正准备量化你的网络，检查下列设置:')
print(f'TARGET PLATFORM      : {QUANT_PLATFROM.name}')
print(f'NETWORK INPUTSHAPE   : {INPUT_SHAPE}')

# ENABLE CUDA KERNEL 会加速量化效率 3x ~ 10x，但是你如果没有装相应编译环境的话是编译不了的
# 你可以尝试安装编译环境，或者在不启动 CUDA KERNEL 的情况下完成量化：移除 with ENABLE_CUDA_KERNEL(): 即可
with ENABLE_CUDA_KERNEL():
    qir = quantize_onnx_model(
        onnx_import_file=MODEL, calib_dataloader=dataloader, calib_steps=128, setting=QS,
        input_shape=INPUT_SHAPE, collate_fn=lambda x: x.to(EXECUTING_DEVICE), 
        platform=QUANT_PLATFROM, do_quantize=True)

    # -------------------------------------------------------------------
    # PPQ 计算量化误差时，使用信噪比的倒数作为指标，即噪声能量 / 信号能量
    # 量化误差 0.1 表示在整体信号中，量化噪声的能量约为 10%
    # 你应当注意，在 graphwise_error_analyse 分析中，我们衡量的是累计误差
    # 网络的最后一层往往都具有较大的累计误差，这些误差是其前面的所有层所共同造成的
    # 你需要使用 layerwise_error_analyse 逐层分析误差的来源
    # -------------------------------------------------------------------
    print('正计算网络量化误差(SNR)，最后一层的误差应小于 0.1 以保证量化精度:')
    reports = graphwise_error_analyse(
        graph=qir, running_device=EXECUTING_DEVICE, steps=32,
        dataloader=dataloader, collate_fn=lambda x: x.to(EXECUTING_DEVICE))
    for op, snr in reports.items():
        if snr > 0.1: ppq_warning(f'层 {op} 的累计量化误差显著，请考虑进行优化')

    if REQUIRE_ANALYZE:
        print('正计算逐层量化误差(SNR)，每一层的独立量化误差应小于 0.1 以保证量化精度:')
        layerwise_error_analyse(graph=qir, running_device=EXECUTING_DEVICE,
                                interested_outputs=None,
                                dataloader=dataloader, collate_fn=lambda x: x.to(EXECUTING_DEVICE))

    print('网络量化结束，正在生成目标文件:')
    export_ppq_graph(
        graph=qir, platform=QUANT_PLATFROM,
        graph_save_to = 'quantized.onnx')
```

**报错如下：**

```shell
Traceback (most recent call last):
  File "/Data1/zengsheng/works/dl_works/ppq_works/yolo_model_zoo/example_onnxruntime.py", line 93, in <module>
  File "/Data2/zengsheng/anaconda3/envs/PPQ/lib/python3.9/site-packages/ppq/api/interface.py", line 590, in export_ppq_graph
    exporter.export(file_path=graph_save_to, config_path=config_save_to, graph=graph, **kwargs)
  File "/Data2/zengsheng/anaconda3/envs/PPQ/lib/python3.9/site-packages/ppq/parser/onnxruntime_exporter.py", line 559, in export
    _nodes.append(super().build_operator_proto(operation))
  File "/Data2/zengsheng/anaconda3/envs/PPQ/lib/python3.9/site-packages/ppq/parser/onnx_exporter.py", line 213, in build_operator_proto
    op_proto = helper.make_node(
  File "/Data2/zengsheng/anaconda3/envs/PPQ/lib/python3.9/site-packages/onnx/helper.py", line 112, in make_node
    node.attribute.extend(
  File "/Data2/zengsheng/anaconda3/envs/PPQ/lib/python3.9/site-packages/onnx/helper.py", line 113, in <genexpr>
    make_attribute(key, value)
  File "/Data2/zengsheng/anaconda3/envs/PPQ/lib/python3.9/site-packages/onnx/helper.py", line 397, in make_attribute
    raise TypeError(
TypeError: value "None" is not valid attribute data type.

```

**Comment by ZhangZhiPku** [comment]
看起来是你的模型中有什么奇奇怪怪的属性，您可以把模型发给我吗？

**Comment by ZhangZhiPku** [comment]
抱歉，我们最近一直在捣鼓大模型，但是我使用最新的PPQ代码运行您的程序好像...啥问题也没有...您是不是需要更新一下PPQ？
