### ISSUE TITLE
执行python setup.py install报错： 动态链接库(DLL)初始化例程失败，如何解决

### ISSUE THREAD

**Issue by wyyt1202** [openppl-public/ppq#577]
(mytorch) E:\learn_file\python\Quantify\ppq>python setup.py install
E:\learn_file\python\Quantify\ppq\ppq\__init__.py:10: UserWarning: You are importing ppq within its own root folder (E:\learn_file\python\Quantify\ppq). 
  warnings.warn(message.format(os.getcwd()))

      ____  ____  __   ____                    __              __
     / __ \/ __ \/ /  / __ \__  ______ _____  / /_____  ____  / /
    / /_/ / /_/ / /  / / / / / / / __ `/ __ \/ __/ __ \/ __ \/ /
   / ____/ ____/ /__/ /_/ / /_/ / /_/ / / / / /_/ /_/ / /_/ / /
  /_/   /_/   /_____\___\_\__,_/\__,_/_/ /_/\__/\____/\____/_/

Traceback (most recent call last):
  File "E:\learn_file\python\Quantify\ppq\setup.py", line 2, in <module>
    from ppq.core import PPQ_CONFIG
  File "E:\learn_file\python\Quantify\ppq\ppq\__init__.py", line 13, in <module>
    from ppq.api.setting import (ActivationQuantizationSetting, DispatchingTable,
  File "E:\learn_file\python\Quantify\ppq\ppq\api\__init__.py", line 1, in <module>
    from ppq.lib import (register_calibration_observer, register_network_exporter,
  File "E:\learn_file\python\Quantify\ppq\ppq\lib\__init__.py", line 44, in <module>
    from .extension import (register_calibration_observer,
  File "E:\learn_file\python\Quantify\ppq\ppq\lib\extension.py", line 7, in <module>
    from .common import __EXPORTERS__, __PARSERS__, __QUANTIZER_COLLECTION__
  File "E:\learn_file\python\Quantify\ppq\ppq\lib\common.py", line 2, in <module>
    from ppq.parser import (AscendExporter, CaffeExporter, CaffeParser,
  File "E:\learn_file\python\Quantify\ppq\ppq\parser\__init__.py", line 9, in <module>
    from .nxp_exporter import NxpExporter
  File "E:\learn_file\python\Quantify\ppq\ppq\parser\nxp_exporter.py", line 1, in <module>
    import onnx
  File "D:\App\Anaconda\envs\mytorch\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。

**Comment by wangtiance** [comment]
你的onnx是不是1.17，我试过降级到1.16.1可以：

https://blog.csdn.net/qq_38702496/article/details/141052666
