### ISSUE TITLE
openvino量化后，无法推理

### ISSUE THREAD

**Issue by gogocoded** [openppl-public/ppq#584]
请教一个问题，我使用例子量化yolov5s模型，导出到openvino平台无法推理，错误提示如下：
Traceback (most recent call last):
  File "D:\v6sp3_sp_quan\ProgramEntrance_openvino.py", line 63, in <module>
    model = openvino_executor.read_model(model="model_int8.onnx"), device_name="CPU")
  File "D:\anaconda3\lib\site-packages\openvino\runtime\ie_api.py", line 511, in read_model
    return Model(super().read_model(model))
RuntimeError: Exception from src\inference\src\core.cpp:85:
Check 'error_message.empty()' failed at src\frontends\onnx\frontend\src\frontend.cpp:124:
Errors during ONNX translation: 
Check '(data_et.is_static())' failed at src\frontends\onnx\frontend\src\op\quantize_linear.cpp:56:
While validating ONNX node '<Node(QuantizeLinear): PPQ_Operation_318>':
"x" input data type must be static.
While validating ONNX node '<Node(Conv): /model.9/cv1/conv/Conv>':
Check 'data.get_partial_shape().rank().is_static()' failed at src\frontends\onnx\frontend\src\op\conv.cpp:44:
The input data tensor's rank has to be known (static)
Check '(data_et.is_static())' failed at src\frontends\onnx\frontend\src\op\quantize_linear.cpp:56:
While validating ONNX node '<Node(QuantizeLinear): PPQ_Operation_310>':
"x" input data type must be static.
While validating ONNX node '<Node(Conv): /model.8/cv3/conv/Conv>':
Check 'data.get_partial_shape().rank().is_static()' failed at src\frontends\onnx\frontend\src\op\conv.cpp:44:
The input data tensor's rank has to be known (static)
Check '(data_et.is_static())' failed at src\frontends\onnx\frontend\src\op\quantize_linear.cpp:56:
While validating ONNX node '<Node(QuantizeLinear): PPQ_Operation_296>':
"x" input data type must be static.
While validating ONNX node '<Node(Conv): /model.8/cv2/conv/Conv>':
Check 'data.get_partial_shape().rank().is_static()' failed at src\frontends\onnx\frontend\src\op\conv.cpp:44:
The input data tensor's rank has to be known (static)
Check '(data_et.is_static())' failed at src\frontends\onnx\frontend\src\op\quantize_linear.cpp:56:
While validating ONNX node '<Node(QuantizeLinear): PPQ_Operation_258>':
"x" input data type must be static.
。。。。

**Comment by ZhangZhiPku** [comment]
看起来openvino不支持动态输入，你需要在导出网络的时候设置其输入输出为静态形状

**Comment by gogocoded** [comment]
求教如何改为静态输入输出？
export_ppq_graph(
    graph=qir, platform=QUANT_PLATFROM,
    graph_save_to = 'model_int8.onnx')

**Comment by gogocoded** [comment]
> 看起来openvino不支持动态输入，你需要在导出网络的时候设置其输入输出为静态形状

求教如何改为静态输入输出？
export_ppq_graph(
graph=qir, platform=QUANT_PLATFROM,
graph_save_to = 'model_int8.onnx')

**Comment by Goo-Leo** [comment]
> > 看起来openvino不支持动态输入，你需要在导出网络的时候设置其输入输出为静态形状
> 
> 求教如何改为静态输入输出？
> export_ppq_graph(
> graph=qir, platform=QUANT_PLATFROM,
> graph_save_to = 'model_int8.onnx')

推理的时候指定输入维度就行，其次openvino现在是支持动态维度的，查看一下官方的手册
