### ISSUE TITLE
构建engine失败，返回None

### ISSUE THREAD

**Issue by jishenghuang** [openppl-public/ppq#585]
Traceback (most recent call last):
  File "/workspace/ppq/ppq/samples/TensorRT/Example_Fp32.py", line 17, in <module>
    builder.create_engine(engine_path='Output/yolov8s.engine', precision="fp16")
  File "/workspace/ppq/ppq/samples/TensorRT/trt_infer.py", line 259, in create_engine
    log.info("Serializing engine to file: {:}".format(engine_path))
AttributeError: 'NoneType' object has no attribute 'serialize'
我发现  是这里的engine返回值为None，怎么解决呢     
        engine = self.builder.build_engine(self.network, self.config)
        print(engine)
        if not engine:
            log.error("Failed to build the TensorRT engine")
        with open(engine_path, "wb") as f:
            log.info("Serializing engine to file: {:}".format(engine_path))
            f.write(engine.serialize())

**Comment by ZhangZhiPku** [comment]
这个说明tensorrt解析onnx文件失败了，你需要观察他更具体的错误
